### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by dzheltkov** [Donskoy-Andrey/Point_In_Polygon#2]
1) Первое задание зачтено.

2) Второе задание зачтено.

3) Для того, чтобы зачёл третье задание нужно модифицировать парсинг аргументов командной строки, чтобы он использовал или только C функцию для конвертации, или только C++ функцию для конвертации, а так же добавить обработку ошибок при чтении из файла (с помощью перечислимого типа, можете также использовать исключения, если поняли как они работают).

4) Сохранять углы в вектор нет смысла, вместо этого их можно сразу обрабатывать.

**Comment by AndreiDonskoi** [comment]
@dzheltkov, переписал алгоритм парсинга параметров из командной строки и значений из файла с помощью stream-функций (как я понял, это и есть с++ формат). 

Теперь есть проверка на то, чтобы в каждой строке файла было ровно 2 значения, которые к тому же конвертируются в double. Аналогично с командной строкой (вводимые координаты х и у).

Также убрал ненужное сохранение углов и лишний цикл в связи с этим.

**Comment by dzheltkov** [comment]
Да, теперь всё хорошо, третье задание зачтено.
